name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: Ruban-07/podcast-generator@main
